Get selected values from dropdowns
UnosquareBelfast/CVGenerator-frontend pull request #18
Opened 2019-11-14 19:19 UTC by fillips-uno

Resolves [CG-40](https://unosquarebelfast.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=CG&modal=detail&selectedIssue=CG-40)

2019-11-18 14:13 UTC, girwin90 requested changes

2019-11-18 14:13 UTC, girwin90 commented on src/components/GenerateCVButton/container.js
> +import { getEmployee, getTemplate } from '../../store/reducers/selected-options';
Can we use an alias here?

2019-11-18 14:13 UTC, girwin90 commented on src/components/common/Select/container.js
> +function mapDispatchToProps(dispatch) {
can we make this an anonymous function just for consistency across the app?

2019-11-18 14:13 UTC, girwin90 commented on src/components/common/Select/container.js
> +/* eslint-enable react/destructuring-assignment */
is this needed? Can we not do this in an eslint file?

2019-11-18 14:13 UTC, girwin90 commented on src/components/constants.js
> +  employee: 'selectComponentEmployee',
Capital letters for keys in a constant object.

2019-11-18 14:13 UTC, girwin90 commented on src/pages/Selector/container.jsx
> +      /* eslint-disable no-shadow */
Can we do this in an eslint rc file or something? Looks just a bit messy in my opinion

2019-11-18 14:13 UTC, girwin90 commented on src/store/actions/action-types.js
> +export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
Nice!

2019-11-18 14:13 UTC, girwin90 commented on src/store/reducers/index.js
> +export const getEmployee = store => FromSelectedOptions.getEmployee(store[EMPLOYEES]);
Are these selectors? Maybe they can be elsewhere?

2019-11-20 13:52 UTC, BrownMark approved these changes
Looks great, all coming together pretty well :)

2019-11-20 13:55 UTC, merged