Sharable Select component
UnosquareBelfast/CVGenerator-frontend pull request #9
Opened 2019-10-30 15:27 UTC by fillips-uno

Resolves [CG12](https://unosquarebelfast.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=CG&modal=detail&selectedIssue=CG-12)

There is a bug in react-select that causes the top option to always be in focus. Ticket to fix when the next release goes out - https://unosquarebelfast.atlassian.net/browse/CG-27

**Mobile View**
![selectComponentMobileView](https://user-images.githubusercontent.com/55099973/67872376-c5117f80-fb29-11e9-9a27-81589e255027.gif)

2019-10-30 15:58 UTC, BrownMark requested changes
One small thing, but looking really well :)

2019-10-30 15:58 UTC, BrownMark commented on src/__tests__/components/common/Select/index.jsx
> +import 'SetupTests';
you should need to include setuptests in each test file. 
```
"jest": {
    "setupTestFrameworkScriptFile": "./setupTests.js",

```

Adding that to package.json should work

2019-10-30 16:00 UTC, BrownMark commented on src/__tests__/components/common/Select/index.jsx
> +import 'SetupTests';
or possibly the jest.config.json

2019-10-30 16:02 UTC, girwin90 approved these changes
Minor comments. Still approving. Good graft, following the pattern and it all looks tidy. Nice going.

2019-10-30 16:02 UTC, girwin90 commented on src/components/common/Label/index.jsx
> +    {text} {isRequired && <span>*</span>}
Nice

2019-10-30 16:02 UTC, girwin90 commented on src/components/common/Select/index.jsx
> +export default SelectComponent;
A nit pick, sorry! I prefer if the export is at the bottom of the file. If you disagree, happy to discuss!

2019-10-31 15:23 UTC, BrownMark requested changes

2019-10-31 15:23 UTC, BrownMark commented on src/components/common/Select/index.jsx
> +  const triggerOnChange = e => {
is this needed? Might be able to remove it and just handleOnChange passed as a prop.

2019-10-31 15:48 UTC, BrownMark requested changes
just 2 super minor things

2019-10-31 15:48 UTC, BrownMark commented on src/components/common/Select/container.jsx
> +  class Container extends React.Component {
don't need to add Container here. 

```
class extends React.Component {
```

2019-10-31 15:48 UTC, BrownMark commented on src/components/common/Select/container.jsx
> +const SelectContainer = Wrapped =>
this can be

```
export default Wrapped =>
```

2019-10-31 17:16 UTC, girwin90 requested changes

2019-10-31 17:16 UTC, girwin90 commented on src/components/common/Select/container.jsx
> +      console.log('selected: ', selected);
A log is here?

2019-10-31 17:16 UTC, girwin90 commented on src/components/common/Select/index.jsx
> +  console.log('options', options);
Debug here.

2019-10-31 17:16 UTC, girwin90 commented on src/components/common/Select/index.jsx
> +export default SelectContainer(SelectComponent);
I'd drop this below the prop types.

2019-11-04 11:29 UTC, fillips-uno commented on src/__tests__/components/common/Select/index.jsx
> +import 'SetupTests';
I created an alias and imported this on line 5

2019-11-04 13:35 UTC, BrownMark approved these changes

2019-11-04 14:01 UTC, merged